J#46602 Linkage standards status changed to Draft to align with FMM=0
HL7/fhir pull request #3144
Opened 2024-08-09 13:27 UTC by michelle-m-miller

## Description

J#46602 Linkage standards status changed to Draft to align with FMM=0

2024-08-09 20:02 UTC, lmckenzi requested changes
Why is this going to draft?  I think the FMM should be moving up and it should remain STU?  This is probably actually one of those that may go normative in R6...

2024-08-09 20:36 UTC, michelle-m-miller commented
@lmckenzi  FMM=0 implies it must be Draft status per https://build.fhir.org/versions.html#maturity, which says

> the artifact has been published on the current build. Artifacts with this level must have a standards status of [Draft](https://build.fhir.org/versions.html#draft).

Patient Care did discuss whether we, instead, wanted to keep the Trial Use standards status and elevate FMM = 1, but the committee was NOT ready to vote that "they consider the artifact substantially complete and ready for implementation".  Just the opposite.  There was some discussion about even deleting the resource all together!

2024-08-09 22:08 UTC, lmckenzi commented
It's been through a few ballots and publications.  It's not in a "we're working on it" state.  It's functionally done.  It hasn't been widely implemented, so calling it a '1' is reasonable.  "0" means "we're part-way through developing this, but we know there are specific changes still needed.  That's not the state the resource is in.  It was FMM 0 originally because it was introduced post-ballot and therefore couldn't be called STU.  But that's definitely not the case anymore.  It definitely meets the requirement for FMM 1.

If the WG feels there's no longer a need for the use-cases the resource is intended to satisfy, it could be removed.  However, if the use-cases are still valid and the resource 'works', it's a patient-centric resource and therefore falls within the scope of the resources that will be de-facto normative in R6.

2024-08-10 02:22 UTC, lmckenzi approved these changes

2024-08-10 21:50 UTC, merged