Changed a relative text-only URL to a full URL in the NamingSystemIdentifierType codesystem
HL7/fhir pull request #3205
Opened 2024-10-31 22:17 UTC by gaurav

## HL7 FHIR Pull Request

_Note: No pull requests will be accepted against `./source` unless logged in the_ [HL7 Jira issue tracker](https://jira.hl7.org/projects/FHIR/issues/).

If you made changes to any files within `./source` please indicate the Jira tracker number this pull request is associated with: `FHIR-42696`

## Description

_Please describe your pull request here._

As per [FHIR-42696](https://jira.hl7.org/browse/FHIR-42696), this PR changes a relative text-only URL (rdf.html#iri-stem) to a full URL (http://hl7.org/fhir/rdf.html#iri-stem).

2024-11-01 20:21 UTC, grahamegrieve commented
why is this a good change? I believe it is a wrong change to make. And which committee authorised it?

2024-11-02 20:55 UTC, gaurav commented
@grahamegrieve Sorry if I skipped a step, Grahame! I'm used to the UTG/Terminology procedures, where a PR is created before submitting an issue for review. The FHIR ticket associated with this change (https://jira.hl7.org/browse/FHIR-42696) has been triaged as Highest priority since last September, so I though that creating a PR for it might help people evaluate it and then decide if it's a worthwhile change or to reject it. I'll move this PR back into Draft status and -- if you'd like -- I could close it and/or delete it as well.

As to why it is a good change, other entries on http://hl7.org/fhir/R5/codesystem-namingsystem-identifier-type.html use absolute URLs (`http://unitsofmeasure.org`), even for HL7 resources (`http://www.hl7.org/Special/committees/vocab/table_0396/index.cfm`), which is why I assumed (incorrectly?) that the reference to `rdf.html` should be absolute as well. Since these local references are not converted into links, I was unsure if a reader would know to copy and paste the local reference into the current URL to get to that location in the FHIR documentation. But if this is the standard for local references in FHIR, then absolutely this entry should follow that guideline as well, and the proposed change (https://jira.hl7.org/browse/FHIR-42696) should be rejected.

2025-02-04 18:32 UTC, lmckenzi requested changes
This should be a hyperlink rather than just writing out the full URL.

2025-02-04 19:07 UTC, gaurav commented
> This should be a hyperlink rather than just writing out the full URL.

Thanks, Lloyd! Do you have an example of what this should look like? I'm not sure how to insert a hypertext into a `value` attribute.

(I was also following the convention currently used by other definitions in this field, such as for `uri` and `v2csmnemonic` -- maybe we should change those as well?)

2025-03-11 22:48 UTC, lmckenzi approved these changes

2025-03-14 01:06 UTC, grahamegrieve approved these changes
ok - found the authority

2025-03-14 01:07 UTC, merged